Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1902:16)
    at listenInCluster (node:net:1959:12)
    at Server.listen (node:net:2061:7)
    at Object.<anonymous> (/Users/tejashsingh/Downloads/taxi_driver_node-main/app.js:70:8)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)Error: Unknown database 'taxi_app'
    at Packet.asError (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/packets/packet.js:738:17)
    at ClientHandshake.execute (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)Error: Unknown database 'taxi_app'
    at Packet.asError (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/packets/packet.js:738:17)
    at ClientHandshake.execute (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)Error: Unknown database 'taxi_app'
    at Packet.asError (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/packets/packet.js:738:17)
    at ClientHandshake.execute (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/tejashsingh/Downloads/taxi_driver_node-main/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)